flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0;
        policy drop;
        iif lo accept
        ct state established,related accept
        tcp dport 22 accept  # SSH
        udp dport 51820 accept  # WireGuard
        ip protocol icmp accept
    }
    chain forward {
        type filter hook forward priority 0;
        policy drop;
        ct state established,related accept
    }
}